num1 =30;
num2 = 20;
sum=num1 + num2;
console.log("The sum of " + num1 + " and " + num2 + " is: " + sum);
difference=num1 - num2;
console.log("The difference of " + num1 + " and " + num2 + " is: " + difference);
product=num1 * num2;    
console.log("The product of " + num1 + " and " + num2 + " is: " + product);
quotient=num1 / num2;
console.log("The quotient of " + num1 + " and " + num2 + " is: " + quotient);